// addSbtPlugin("org.tpolecat" % "tut-plugin" % "0.6.9")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
